const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const server=require('http').createServer((req,res)=>{const f=path.join(process.cwd(),'site',req.url==='/'?'index.html':new URL(req.url,'http://localhost').pathname);try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8080,r));
 const browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:path.resolve(process.env.CHROMIUM_PATH)}:{}),args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--no-zygote'],headless:true});
 try{
 const page=await browser.newPage({deviceScaleFactor:2,viewport:{width:1400,height:1800}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://localhost:8080')&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))requests.push(r.url());});page.on('dialog',async d=>{console.log('DIALOG',d.message().slice(0,150));await d.accept();});
 await page.goto('http://localhost:8080');await page.locator('#primaryNav [data-route=data]').click();
 const apply=async()=>{await page.locator('#applyImport').waitFor({timeout:30000});await page.locator('#applyImport').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Import voltooid')||document.querySelector('#status').classList.contains('error'),{},{timeout:180000});const s=await page.locator('#status').innerText();console.log(s);assert(s.includes('Import voltooid'));};
 // Check original MS Project parser and restored settings before the large DVM import.
 const xml='<?xml version="1.0"?><Project xmlns="http://schemas.microsoft.com/project"><Name>Testplanning</Name><StartDate>2026-09-01T08:00:00</StartDate><FinishDate>2026-09-30T17:00:00</FinishDate><Tasks><Task><UID>1</UID><ID>1</ID><Name>VWM</Name><OutlineLevel>1</OutlineLevel><OutlineNumber>1</OutlineNumber><Summary>1</Summary><Start>2026-09-01T08:00:00</Start><Finish>2026-09-30T17:00:00</Finish></Task><Task><UID>2</UID><ID>2</ID><Name>A2 onderhoud</Name><OutlineLevel>2</OutlineLevel><OutlineNumber>1.1</OutlineNumber><Summary>0</Summary><Start>2026-09-02T08:00:00</Start><Finish>2026-09-05T17:00:00</Finish><Duration>PT32H0M0S</Duration></Task></Tasks></Project>';
 await page.locator('#files').setInputFiles({name:'testplanning.xml',mimeType:'text/xml',buffer:Buffer.from(xml)});await apply();
 let bi=page.frames().find(f=>f.url().endsWith('/bi.html'));console.log('PLANNING',await bi.evaluate(()=>HUB.summary().planning));assert((await bi.evaluate(()=>HUB.summary().planning.regels))>0);
 const p6='<APIBusinessObjects><Project><ObjectId>1</ObjectId><Name>P6 test</Name><WBS><ObjectId>10</ObjectId><Name>VWM</Name><ParentObjectId>0</ParentObjectId></WBS><Activity><ObjectId>20</ObjectId><Id>A20</Id><Name>Onderhoud</Name><WBSObjectId>10</WBSObjectId><StartDate>2026-09-01T08:00:00</StartDate><FinishDate>2026-09-03T17:00:00</FinishDate><Type>Task Dependent</Type></Activity><ResourceAssignment><ActivityObjectId>20</ActivityObjectId><ResourceObjectId>30</ResourceObjectId><PlannedUnitsPerTime>2</PlannedUnitsPerTime></ResourceAssignment></Project><Resource><ObjectId>30</ObjectId><Name>Begeleiding</Name></Resource></APIBusinessObjects>';
 await page.locator('#files').setInputFiles({name:'testp6.xml',mimeType:'text/xml',buffer:Buffer.from(p6)});await apply();
 console.log('P6',await bi.evaluate(()=>({planning:HUB.summary().planning,fte:HUB.export().p6Capaciteit?.totFte})));assert.equal(await bi.evaluate(()=>HUB.export().p6Capaciteit?.totFte),2);assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 await page.locator('#primaryNav [data-route=planning]').click();
 const pl=page.frames().find(f=>new URL(f.url()).pathname.endsWith('/planning.html'));
 await pl.locator('#iplCanvas').waitFor({state:'visible'});await pl.locator('#iplCanvas').scrollIntoViewIfNeeded();assert((await pl.locator('#iplCanvas').boundingBox()).height>40);assert(await pl.locator('#kpi-bar').isHidden());
 

 await page.locator('#primaryNav [data-route=data]').click();
 const activities=Array.from({length:4000},(_,i)=>{const year=2022+Math.floor(i/300),month=String(i%12+1).padStart(2,'0');return `<Activity><ObjectId>${i+100}</ObjectId><Id>A${i}</Id><Name>Taak ${i}</Name><WBSObjectId>10</WBSObjectId><StartDate>${year}-${month}-01T08:00:00</StartDate><FinishDate>${year}-${month}-20T17:00:00</FinishDate><Type>Task Dependent</Type></Activity>`;}).join('');
 const large='<APIBusinessObjects><Project><ObjectId>1</ObjectId><Name>Grote testplanning</Name><WBS><ObjectId>10</ObjectId><Name>VWM</Name><ParentObjectId>0</ParentObjectId></WBS>'+activities+'</Project></APIBusinessObjects>';
 await page.locator('#files').setInputFiles({name:'grote-testplanning.xml',mimeType:'text/xml',buffer:Buffer.from(large)});await apply();await page.locator('#primaryNav [data-route=planning]').click();
 await pl.waitForFunction(()=>IPL_LAYOUT&&IPL_MODEL.regels.length===4000);await pl.evaluate(()=>ipl_setTimeScale('quarter'));
 const checkPixels=()=>pl.evaluate(()=>{const c=document.getElementById('iplCanvas'),l=IPL_LAYOUT,d=c.width/parseFloat(c.style.width),w=parseFloat(c.style.width),h=parseFloat(c.style.height);const bars=l.layout.filter(r=>!r.mile&&r.bx2>l.offsetX+5&&r.bx<l.offsetX+w-5&&r.cy>l.offsetY+5&&r.cy<l.offsetY+h-5);if(!bars.length)throw Error('Geen zichtbare activiteit');const r=bars[bars.length-1],x=Math.max(l.offsetX+3,Math.min(l.offsetX+w-3,(r.bx+r.bx2)/2)),y=r.cy;return {pixels:c.width*c.height,width:c.width,height:c.height,alpha:c.getContext('2d').getImageData(Math.floor((x-l.offsetX)*d),Math.floor((y-l.offsetY)*d),1,1).data[3],id:r.id,x:x-l.offsetX,y:y-l.offsetY,dx:l.plotW/(IPL_TEND-IPL_TSTART)/12,offsetX:l.offsetX,offsetY:l.offsetY};});
 const first=await checkPixels();assert.equal(first.alpha,255);assert(first.pixels<=4200000);console.log('Grote planning zichtbaar',first.width,first.height);
 await pl.evaluate(()=>{const c=document.getElementById('iplCanvas'),h=c.parentElement,last=ipl_buildOrdered().filter(r=>r.type==='regel').at(-1).regel;h.scrollTop=h.scrollHeight;h.scrollLeft=IPL_LAYOUT.X(last.t0)-h.clientWidth/2;});
 await pl.waitForFunction(()=>IPL_LAYOUT.offsetY>60000&&IPL_LAYOUT.offsetX>1000);const last=await checkPixels();assert.equal(last.alpha,255);assert(last.pixels<=4200000);
 await pl.locator('#iplCanvas').scrollIntoViewIfNeeded();const box=await pl.locator('#iplCanvas').boundingBox();await page.mouse.move(box.x+last.x,box.y+last.y);await page.mouse.down();await page.mouse.move(box.x+last.x+last.dx,box.y+last.y,{steps:4});await page.mouse.up();assert.equal(await pl.evaluate(id=>IPL_MSHIFT[id],last.id),1);
 await pl.evaluate(()=>{IPL_TIMESCALE='week';renderIPL();const h=document.getElementById('iplCanvas').parentElement,last=ipl_buildOrdered().filter(r=>r.type==='regel').at(-1).regel;h.scrollLeft=IPL_LAYOUT.X(last.t0)-h.clientWidth/2;});await pl.waitForFunction(()=>IPL_LAYOUT.offsetX>10000);const week=await checkPixels();assert.equal(week.alpha,255);assert(week.pixels<=4200000);
 await pl.evaluate(()=>{const h=document.getElementById('iplCanvas').parentElement;h.scrollTop=0;h.scrollLeft=0;ipl_expandAll(false);});await pl.waitForFunction(()=>IPL_LAYOUT.offsetY===0);assert(await pl.evaluate(()=>document.getElementById('iplCanvas').height)<200);
 await pl.evaluate(()=>ipl_expandAll(true));await pl.waitForFunction(()=>IPL_LAYOUT.layout.length>0);
 await page.setViewportSize({width:1500,height:950});await page.waitForTimeout(250);assert((await checkPixels()).pixels<=4200000);
 await page.reload();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Werkruimte gereed'),{},{timeout:180000});await page.locator('#primaryNav [data-route=planning]').click();const restoredLarge=page.frames().find(f=>new URL(f.url()).pathname.endsWith('/planning.html'));await restoredLarge.waitForFunction(()=>IPL_MODEL?.regels.length===4000&&IPL_LAYOUT?.layout.length>0);
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);console.log('Large XML, visible pixels, both scroll directions, drag, zoom, collapse, resize and restore passed');

 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
